apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.app.name }}
  namespace: praveen-ns
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  minReadySeconds: {{ .Values.mysql.minReadySeconds }}
  selector:
    matchLabels:
      app: mysql
  updateStrategy:
    type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 0
    #   maxSurge: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: {{ .Values.mysql.terminationGracePeriodSeconds }}
      containers:
      - name: mysql-container 
        image: mysql
        ports:
        - containerPort: {{ .Values.mysql.ports.port }}
        resources:
          requests:
            memory: {{ .Values.mysql.resources.requests.memory }}
            cpu: {{ .Values.mysql.resources.requests.cpu }}
          limits:
            memory: {{ .Values.mysql.resources.limits.memory }}
            cpu: {{ .Values.mysql.resources.limits.cpu }}
        # env:
        #   - name: MYSQL_ROOT_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: duni-secret
        #         key: MYSQL_ROOT_PASSWORD
          
        #   - name: MYSQL_USER
        #     valueFrom:
        #       configMapKeyRef:
        #         name: duni-config
        #         key: DB_USER
            
        #   - name: MYSQL_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: duni-secret
        #         key: DB_PASSWORD
          
        #   - name: DB_HOST
        #     valueFrom:
        #       configMapKeyRef:
        #         name: duni-config
        #         key: DB_HOST

        envFrom:
          - configMapRef:
              name: duni-config
          - secretRef:
              name: duni-secret
          
        volumeMounts:
        - name: {{ .Values.mysql.vct.name }}
          mountPath: /var/lib/mysql 

        - name: initdb-volume
          mountPath: /docker-entrypoint-initdb.d

      volumes:        
        - name: initdb-volume
          configMap:
            name: mysql-initdb
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.mysql.vct.name }}
      spec:
        accessModes: {{ .Values.mysql.vct.accessModes }}
        storageClassName: {{ .Values.sc.name }}
        resources:
          requests:
            storage: {{ .Values.mysql.vct.resources.requests.storage }}
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
  namespace: praveen-ns
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - name: mysql
    port: {{ .Values.mysql.hostPort }}
    targetPort: {{ .Values.mysql.ports.port }}