apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.sc.name }} 
provisioner: {{ .Values.sc.provisioner }}
parameters:
  server: {{ .Values.sc.server }}
  share: {{ .Values.sc.share }}