apiVersion: v1
kind: ConfigMap
metadata:
  name: duni-config
  namespace: praveen-ns 
data:
  DB_USER: "college_user"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  GRIEVANCE_DB: "grievance_db"
  LEAVE_DB: "leave_db"
  TIMETABLE_DB: "timetable_db"
  EXAMS_DB: "exams_db"
