apiVersion: v1
kind: Secret
metadata:
  name: duni-secret
  namespace: praveen-ns 
stringData:
  MYSQL_ROOT_PASSWORD: "Root@123"
  MYSQL_DATABASE: mariadb
  MYSQLDB_USER: "college_user"
  MYSQLDB_PASSWORD: "deereddy@123"